sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '12'
before_install:
  - npm install -g codecov
install: echo "install happens as part of setup"
script: npm run setup
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R
    spec
  - codecov
# npx codecov@3
# branches:
# feature/jest
# only: master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
