describe('anonymous calculator', () => {
  it('can make calculations', () => {
    cy.visit('/')
      .get('.Vg8TIC_Y51UXScRRk9MR > :nth-child(3)')
      .click()
      .get('.GofTyXI7GJi62IaMkcx2 > :nth-child(4)')
      .click()
      .get('.Vg8TIC_Y51UXScRRk9MR > :nth-child(4)')
      .click()
      .get('.GofTyXI7GJi62IaMkcx2 > :nth-child(5)')
      .click()
      .get('[data-testid=total]')
      .should('have.text', '3')
  })
})
